"""Remove unique constraint from direct_requests to allow multiple requests over time

Revision ID: 1875a00f1180
Revises: 880ac5d2f83e
Create Date: 2025-11-18 19:28:05.248908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1875a00f1180'
down_revision = '880ac5d2f83e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('direct_requests', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('unique_request_pair'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('direct_requests', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('unique_request_pair'), ['sender_uid', 'receiver_uid'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
