"""Change age to date_of_birth and drop school

Revision ID: 5010fc30c30c
Revises: 10346f23bc84
Create Date: 2025-11-17 21:18:27.841574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5010fc30c30c'
down_revision = '10346f23bc84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_of_birth', sa.Date(), nullable=False))
        batch_op.drop_column('age')
        batch_op.drop_column('school')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('date_of_birth')

    # ### end Alembic commands ###
