"""Add direct requests table

Revision ID: 880ac5d2f83e
Revises: d6d67005386c
Create Date: 2025-11-18 13:43:51.668702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '880ac5d2f83e'
down_revision = 'd6d67005386c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('direct_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_uid', sa.String(), nullable=False),
    sa.Column('receiver_uid', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='requeststatus'), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['receiver_uid'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['sender_uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sender_uid', 'receiver_uid', name='unique_request_pair')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('direct_requests')
    # ### end Alembic commands ###
