"""add_group_requests_table

Revision ID: bb24e514dbe7
Revises: a27f21fc7e07
Create Date: 2025-11-19 17:10:33.516521

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bb24e514dbe7'
down_revision = 'a27f21fc7e07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_uid', sa.String(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='grouprequeststatus'), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['requester_uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requester_uid', 'group_id', 'status', name='unique_pending_group_request')
    )
    with op.batch_alter_table('group_courses', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_index(batch_op.f('idx_group_courses_course_id'))
        batch_op.drop_index(batch_op.f('idx_group_courses_group_id'))
        batch_op.drop_constraint(batch_op.f('group_courses_course_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('group_courses_group_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'groups', ['group_id'], ['id'])
        batch_op.create_foreign_key(None, 'courses', ['course_id'], ['course_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_courses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('group_courses_group_id_fkey'), 'groups', ['group_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('group_courses_course_id_fkey'), 'courses', ['course_id'], ['course_id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_group_courses_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_group_courses_course_id'), ['course_id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    op.drop_table('group_requests')
    # ### end Alembic commands ###
