"""add_username_and_enum_fields

Revision ID: d6d67005386c
Revises: 5010fc30c30c
Create Date: 2025-11-18 12:57:25.268451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6d67005386c'
down_revision = '5010fc30c30c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create ENUM types first
    grade_enum = sa.Enum('FRESHMAN', 'SOPHOMORE', 'JUNIOR', 'SENIOR', 'POSTGRADUATE', name='grade')
    gender_enum = sa.Enum('MALE', 'FEMALE', 'NON_BINARY', 'PREFER_NOT_TO_SAY', name='gender')
    
    grade_enum.create(op.get_bind(), checkfirst=True)
    gender_enum.create(op.get_bind(), checkfirst=True)
    
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.alter_column('grade',
               existing_type=sa.VARCHAR(),
               type_=grade_enum,
               existing_nullable=False)
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(),
               type_=gender_enum,
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=50), nullable=False))
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('username')

    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=sa.Enum('MALE', 'FEMALE', 'NON_BINARY', 'PREFER_NOT_TO_SAY', name='gender'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
        batch_op.alter_column('grade',
               existing_type=sa.Enum('FRESHMAN', 'SOPHOMORE', 'JUNIOR', 'SENIOR', 'POSTGRADUATE', name='grade'),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    # Drop ENUM types
    sa.Enum(name='gender').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='grade').drop(op.get_bind(), checkfirst=True)
    
    # ### end Alembic commands ###
